project:
  type: website
  pre-render:
    - ./scripts/fetch_publications.py

website:
  favicon: images/roshan_logo_2.png
  site-url: https://roshkjr.github.io
  twitter-card: true
  cookie-consent: true
  google-analytics:
    tracking-id: G-V3RM2PXBNZ
    anonymize-ip: true
  open-graph: true
  navbar:
    logo: images/roshan_logo_2.png
    background: "#0a1121"
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - publications.qmd
      - talks.qmd
      - blogs.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



